const express = require("express");
const { randomUUID } = require("node:crypto");
const ROOT = "/super/tariff-management";
const clone = (value) => JSON.parse(JSON.stringify(value));
const fail = (res, status, code, message, extra = {}) => res.status(status).json({ message, code, ...extra });
const getCatalog = (db) => db.get("superTariffManagementCatalog").value();
const paged = (items, query) => { const page = Math.max(1, Number.parseInt(query.page, 10) || 1); const pageSize = Math.min(100, Math.max(1, Number.parseInt(query.pageSize, 10) || 10)); const values = items.slice().sort((a, b) => String(a.id).localeCompare(String(b.id))); return { items: values.slice((page - 1) * pageSize, page * pageSize), totalCount: values.length, page, pageSize, totalPages: Math.ceil(values.length / pageSize) }; };
module.exports = function registerTariffManagementRoutes(server, router) {
  server.use(ROOT, express.json());
  ["tariffs", "addOns", "packages", "offers"].forEach((type) => {
    server.get(`${ROOT}/${type}`, (req, res) => { let items = getCatalog(router.db)[type] || []; if (req.query.status) items = items.filter((item) => item.status === req.query.status); if (req.query.keyword) { const term = req.query.keyword.toLowerCase(); items = items.filter((item) => JSON.stringify(item).toLowerCase().includes(term)); } return res.json(paged(items, req.query)); });
    server.get(`${ROOT}/${type}/:id`, (req, res) => { const item = (getCatalog(router.db)[type] || []).find((entry) => entry.id === req.params.id); return item ? res.json(item) : fail(res, 404, "CATALOG_ITEM_NOT_FOUND", "Catalog item not found"); });
  });
  server.get(`${ROOT}/overview`, (req, res) => { const data = getCatalog(router.db); return res.json({ generatedAt: new Date().toISOString(), tariffs: data.tariffs.length, addOns: data.addOns.length, packages: data.packages.length, offers: data.offers.length, activeOffers: data.offers.filter((item) => item.status === "active").length, mockOnly: true }); });
  server.post(`${ROOT}/:type`, (req, res) => { const type = req.params.type; if (!["tariffs", "addOns", "packages", "offers"].includes(type)) return fail(res, 404, "UNKNOWN_CATALOG_TYPE", "Unknown catalog type"); if (typeof req.body?.name !== "string" || !req.body.name.trim()) return fail(res, 400, "VALIDATION_ERROR", "A non-empty name is required", { fieldErrors: { name: ["Required"] } }); const data = clone(getCatalog(router.db)); const now = new Date().toISOString(); const item = { ...req.body, id: `${type.slice(0, -1)}-${randomUUID()}`, status: "draft", companyVisible: false, version: 1, createdAt: now, updatedAt: now }; data[type].push(item); data.auditEvents.push({ id: `tariff-audit-${randomUUID()}`, timestamp: now, action: `${type}.created`, entityType: type, entityId: item.id, mockOnly: true }); router.db.set("superTariffManagementCatalog", data).write(); return res.status(201).json({ message: "Draft catalog item created", data: item, mockOnly: true }); });
  server.patch(`${ROOT}/:type/:id`, (req, res) => { const type = req.params.type; const data = clone(getCatalog(router.db)); const index = (data[type] || []).findIndex((item) => item.id === req.params.id); if (index < 0) return fail(res, 404, "CATALOG_ITEM_NOT_FOUND", "Catalog item not found"); if (!Number.isInteger(req.body?.version) || req.body.version !== data[type][index].version) return fail(res, 409, "VERSION_CONFLICT", "Catalog item changed after it was loaded", { currentVersion: data[type][index].version }); const { id, version, ...changes } = req.body; const item = { ...data[type][index], ...changes, id: data[type][index].id, version: data[type][index].version + 1, updatedAt: new Date().toISOString() }; data[type][index] = item; router.db.set("superTariffManagementCatalog", data).write(); return res.json({ message: "Catalog item updated", data: item, mockOnly: true }); });
  server.post(`${ROOT}/:type/:id/:action`, (req, res) => { const target = { activate: "active", schedule: "scheduled", archive: "archived", expire: "expired" }[req.params.action]; const data = clone(getCatalog(router.db)); const item = (data[req.params.type] || []).find((entry) => entry.id === req.params.id); if (!item) return fail(res, 404, "CATALOG_ITEM_NOT_FOUND", "Catalog item not found"); if (!target) return fail(res, 400, "INVALID_ACTION", "Unsupported lifecycle action"); if (!Number.isInteger(req.body?.version) || req.body.version !== item.version) return fail(res, 409, "VERSION_CONFLICT", "Catalog item changed after it was loaded", { currentVersion: item.version }); item.status = target; item.companyVisible = target === "active"; item.version += 1; item.updatedAt = new Date().toISOString(); router.db.set("superTariffManagementCatalog", data).write(); return res.json({ message: "Catalog lifecycle state updated", data: item, mockOnly: true }); });
};
